import {
    createIcons,
    AlertCircle,
    ArrowLeft,
    ArrowRight,
    Award,
    Badge,
    BadgeCheck,
    BadgePercent,
    BarChart3,
    Bell,
    BellOff,
    Bike,
    Boxes,
    Calculator,
    Calendar,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    CircleAlert,
    CircleCheck,
    ClipboardList,
    Clock,
    Code,
    Copy,
    CreditCard,
    Currency,
    Database,
    Download,
    Ellipsis,
    ExternalLink,
    Eye,
    EyeOff,
    File,
    FileText,
    Ghost,
    Group,
    History,
    Home,
    Image,
    Inbox,
    Info,
    Key,
    Landmark,
    LayoutDashboard,
    LayoutGrid,
    Library,
    Link,
    Lock,
    LogOut,
    Logs,
    Mail,
    MapPin,
    Menu,
    MessageCircle,
    Minus,
    Package,
    PackageSearch,
    Pencil,
    Percent,
    Phone,
    Plus,
    Printer,
    Radio,
    Receipt,
    RefreshCw,
    RotateCcw,
    ScrollText,
    Search,
    Settings,
    Shield,
    ShieldCheck,
    ShoppingBag,
    ShoppingCart,
    SlidersHorizontal,
    Star,
    Store,
    Summary,
    Tag,
    Target,
    Trash2,
    TrendingDown,
    TrendingUp,
    TriangleAlert,
    Truck,
    Type,
    Undo2,
    Upload,
    User,
    UserCheck,
    Users,
    Wallet,
    Weight,
    X,
    XCircle,
} from 'lucide';

// ponytail: daftar statis agar bundle tidak memuat ~1.700 ikon. Ikon baru yang belum
// didaftarkan di sini tampil sebagai circle-alert dan memunculkan warning di console.
const icons = {
    AlertCircle,
    ArrowLeft,
    ArrowRight,
    Award,
    Badge,
    BadgeCheck,
    BadgePercent,
    BarChart3,
    Bell,
    BellOff,
    Bike,
    Boxes,
    Calculator,
    Calendar,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    CircleAlert,
    CircleCheck,
    ClipboardList,
    Clock,
    Code,
    Copy,
    CreditCard,
    Currency,
    Database,
    Download,
    Ellipsis,
    ExternalLink,
    Eye,
    EyeOff,
    File,
    FileText,
    Ghost,
    Group,
    History,
    Home,
    Image,
    Inbox,
    Info,
    Key,
    Landmark,
    LayoutDashboard,
    LayoutGrid,
    Library,
    Link,
    Lock,
    LogOut,
    Logs,
    Mail,
    MapPin,
    Menu,
    MessageCircle,
    Minus,
    Package,
    PackageSearch,
    Pencil,
    Percent,
    Phone,
    Plus,
    Printer,
    Radio,
    Receipt,
    RefreshCw,
    RotateCcw,
    ScrollText,
    Search,
    Settings,
    Shield,
    ShieldCheck,
    ShoppingBag,
    ShoppingCart,
    SlidersHorizontal,
    Star,
    Store,
    Summary,
    Tag,
    Target,
    Trash2,
    TrendingDown,
    TrendingUp,
    TriangleAlert,
    Truck,
    Type,
    Undo2,
    Upload,
    User,
    UserCheck,
    Users,
    Wallet,
    Weight,
    X,
    XCircle,
};

const fallbackIconName = 'circle-alert';

function toExportName(name) {
    return name
        .split('-')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join('');
}

function refreshIcons() {
    document.querySelectorAll('[data-lucide]').forEach((element) => {
        const iconName = element.getAttribute('data-lucide');

        if (!icons[toExportName(iconName ?? '')]) {
            console.warn(`[lucide] Missing icon "${iconName}", falling back to "${fallbackIconName}".`);
            element.setAttribute('data-lucide', fallbackIconName);
        }
    });

    createIcons({ icons });
}

document.addEventListener('DOMContentLoaded', refreshIcons);
document.addEventListener('livewire:navigated', refreshIcons);
document.addEventListener('livewire:init', () => {
    Livewire.hook('morph.updated', ({ el }) => {
        if (el?.querySelector?.('[data-lucide]') || el?.hasAttribute?.('data-lucide')) {
            refreshIcons();
        }
    });
});
